/**
 * build-js.js
 * Concatenates the browser app scripts into a single styles-style bundle
 * (scripts/bundle.js) to cut HTTP requests. The files already share global
 * scope across separate <script> tags today, so they are concatenated as-is
 * (NOT wrapped in IIFEs) to preserve cross-file global references.
 *
 * Order matters and mirrors the original <script> order in index.html:
 *   project-loader → renderer → scroll-controller → main → custom-scrollbar → lightbox
 *
 * projects-index.js stays a separate <script> BEFORE this bundle (it is
 * generated data and must load first). analytics.js / clarity.js stay separate
 * (third-party loaders with their own placement).
 *
 * Runs in the build pipeline after generate-project-files; minify.js compresses
 * the resulting bundle.js afterwards.
 */

const fs   = require("fs");
const path = require("path");

const ROOT    = path.join(__dirname, "..");
const SCRIPTS = path.join(ROOT, "scripts");
const OUT     = path.join(SCRIPTS, "bundle.js");

const FILES = [
  "project-loader.js",
  "project-renderer.js",
  "project-scroll-controller.js",
  "main.js",
  "custom-scrollbar.js",
  "lightbox.js",
  "custom-cursor.js",
];

let bundle = "/* Hong Design — JS bundle (generated by scripts/build-js.js) */\n";

for (const file of FILES) {
  const src = fs.readFileSync(path.join(SCRIPTS, file), "utf8");
  bundle += "\n/* === " + file + " === */\n" + src + "\n;\n";
}

fs.writeFileSync(OUT, bundle, "utf8");
console.log("build-js: bundle.js written (" + Math.round(bundle.length / 1024) +
  "KB from " + FILES.length + " files)");
