/**
 * build-css.js
 * Concatenates the three source CSS files into a single bundle (styles/bundle.css)
 * to reduce HTTP round-trips. The mobile.css media query is preserved by wrapping
 * its contents in a @media block inline.
 *
 * Run as part of the build pipeline before prerender.js.
 */

const fs   = require('fs');
const path = require('path');

const ROOT      = path.join(__dirname, '..');
const STYLES    = path.join(ROOT, 'styles');
const OUT       = path.join(STYLES, 'bundle.css');

const files = [
  { file: 'main.css',         media: null },
  { file: 'custom-styles.css', media: null },
  { file: 'mobile.css',       media: '(max-width:768px)' },
];

let bundle = '/* Hong Design — CSS bundle (generated by scripts/build-css.js) */\n\n';

for (const { file, media } of files) {
  const src = fs.readFileSync(path.join(STYLES, file), 'utf8');
  if (media) {
    bundle += `@media ${media} {\n${src}\n}\n\n`;
  } else {
    bundle += `/* === ${file} === */\n${src}\n\n`;
  }
}

fs.writeFileSync(OUT, bundle, 'utf8');
console.log(`build-css: bundle.css written (${Math.round(bundle.length / 1024)}KB from ${files.length} files)`);
